### ISSUE TITLE
个人声明

### ISSUE THREAD

**Issue by DoongLi** [HFUT-CHEATER/HFUTCheaterCollection#9]
本人不是repo的维护者，更不能确保repo信息的可靠性，只是看到老师链接缺失随手PR了一下，所支持的也是整顿作弊风气的行为，请学校领导不要再联系我了orz~

**Comment by Darkexpeller** [comment]
昨天看到学长把issue撤了就猜出来了

**Comment by HFUT-CHEATER** [comment]
堵不如疏，疏不如引
